"use client";

import { useState } from "react";
import { ChevronDown, ChevronRight, Folder, FolderOpen, Sparkles } from "lucide-react";
import { DeckCard } from "@/components/deck-card";
import type { Deck } from "@/lib/schemas/deck";
import { motion, AnimatePresence } from "framer-motion";

interface DeckFolderProps {
    semester: string;
    decks: Deck[];
    defaultOpen?: boolean;
}

export function DeckFolder({ semester, decks, defaultOpen = true }: DeckFolderProps) {
    const [isOpen, setIsOpen] = useState(defaultOpen);
    const isAutoGenerated = semester !== "Other";

    return (
        <div className="bg-white rounded-3xl border border-ace-blue/10 overflow-hidden shadow-sm hover:shadow-md transition-shadow">
            {/* Folder Header - Clickable */}
            <button
                onClick={() => setIsOpen(!isOpen)}
                className="w-full flex items-center gap-4 p-4 hover:bg-cream-50 transition-colors group"
            >
                {/* Folder Icon */}
                <div className={`p-2.5 rounded-xl transition-colors ${isOpen
                        ? "bg-ace-blue/10 text-ace-blue"
                        : "bg-cream-100 text-ace-blue/60 group-hover:bg-ace-blue/10 group-hover:text-ace-blue"
                    }`}>
                    {isOpen ? (
                        <FolderOpen className="h-5 w-5" />
                    ) : (
                        <Folder className="h-5 w-5" />
                    )}
                </div>

                {/* Semester Name */}
                <div className="flex-1 flex items-center gap-3 text-left">
                    <h2 className="font-serif text-xl text-ace-blue font-semibold">
                        {semester}
                    </h2>
                    <span className="text-sm text-ace-blue/50 bg-cream-100 px-2.5 py-0.5 rounded-full">
                        {decks.length} {decks.length === 1 ? "deck" : "decks"}
                    </span>
                    {isAutoGenerated && (
                        <span className="text-xs text-green-600 bg-green-50 px-2 py-0.5 rounded-full flex items-center gap-1">
                            <Sparkles className="h-3 w-3" />
                            Auto-generated
                        </span>
                    )}
                </div>

                {/* Expand/Collapse Icon */}
                <div className={`p-1 rounded-full transition-transform duration-200 ${isOpen ? "rotate-0" : "-rotate-90"}`}>
                    <ChevronDown className="h-5 w-5 text-ace-blue/40" />
                </div>
            </button>

            {/* Collapsible Content */}
            <AnimatePresence initial={false}>
                {isOpen && (
                    <motion.div
                        initial={{ height: 0, opacity: 0 }}
                        animate={{ height: "auto", opacity: 1 }}
                        exit={{ height: 0, opacity: 0 }}
                        transition={{ duration: 0.2, ease: "easeInOut" }}
                        className="overflow-hidden"
                    >
                        <div className="p-4 pt-0 border-t border-ace-blue/5">
                            <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3 pt-4">
                                {decks.map((deck) => (
                                    <DeckCard key={deck.id} deck={deck} />
                                ))}
                            </div>
                        </div>
                    </motion.div>
                )}
            </AnimatePresence>
        </div>
    );
}
