-- Study Plans Table
-- Tracks high-level study goals (e.g., "Ace Calculus Final")

CREATE TABLE IF NOT EXISTS study_plans (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    target_date TIMESTAMPTZ,
    status TEXT NOT NULL DEFAULT 'active', -- 'active', 'completed', 'archived'
    generated_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Plan Milestones Table
-- Structured steps generated by AI to achieve the plan

CREATE TABLE IF NOT EXISTS plan_milestones (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    plan_id UUID REFERENCES study_plans(id) ON DELETE CASCADE NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    date_due TIMESTAMPTZ,
    is_completed BOOLEAN DEFAULT FALSE,
    order_index INTEGER NOT NULL,
    resources JSONB DEFAULT '[]', -- Links to decks, pdfs, etc.
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_study_plans_user ON study_plans(user_id);
CREATE INDEX IF NOT EXISTS idx_plan_milestones_plan ON plan_milestones(plan_id);

-- Enable RLS
ALTER TABLE study_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE plan_milestones ENABLE ROW LEVEL SECURITY;

-- RLS Policies for study_plans
CREATE POLICY "Users can view their own study plans" ON study_plans FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own study plans" ON study_plans FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own study plans" ON study_plans FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete their own study plans" ON study_plans FOR DELETE USING (auth.uid() = user_id);

-- RLS Policies for plan_milestones
-- Milestones are accessed via plans, but we need direct policies too or use a join check
CREATE POLICY "Users can view milestones of their plans" ON plan_milestones FOR SELECT USING (
    EXISTS (SELECT 1 FROM study_plans WHERE study_plans.id = plan_milestones.plan_id AND study_plans.user_id = auth.uid())
);

CREATE POLICY "Users can insert milestones to their plans" ON plan_milestones FOR INSERT WITH CHECK (
    EXISTS (SELECT 1 FROM study_plans WHERE study_plans.id = plan_milestones.plan_id AND study_plans.user_id = auth.uid())
);

CREATE POLICY "Users can update milestones of their plans" ON plan_milestones FOR UPDATE USING (
    EXISTS (SELECT 1 FROM study_plans WHERE study_plans.id = plan_milestones.plan_id AND study_plans.user_id = auth.uid())
);

CREATE POLICY "Users can delete milestones of their plans" ON plan_milestones FOR DELETE USING (
    EXISTS (SELECT 1 FROM study_plans WHERE study_plans.id = plan_milestones.plan_id AND study_plans.user_id = auth.uid())
);
